fos_rest:
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    allowed_methods_listener: true
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    view:
        view_response_listener: true
        formats:
            rss: false
            json: true
            xml: false
        force_redirects:
            html: true
        failed_validation: HTTP_UNPROCESSABLE_ENTITY
        empty_content: HTTP_NO_CONTENT
        default_engine: twig