fos_rest:
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    allowed_methods_listener: true
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    view:
        view_response_listener: true
        formats:
            rss: false
            json: true
            xml: false
        failed_validation: HTTP_UNPROCESSABLE_ENTITY
        empty_content: HTTP_NO_CONTENT